CREATE TABLE [adi].[CCLF5] (
    [URN]                     INT             IDENTITY (1, 1) NOT NULL,
    [CUR_CLM_UNIQ_ID]         NUMERIC (26)    NULL,
    [CLM_LINE_NUM]            INT             NULL,
    [BENE_HIC_NUM]            VARCHAR (22)    NULL,
    [CLM_TYPE_CD]             SMALLINT        NULL,
    [CLM_FROM_DT]             DATE            NULL,
    [CLM_THRU_DT]             DATE            NULL,
    [RNDRG_PRVDR_TYPE_CD]     VARCHAR (3)     NULL,
    [RNDRG_PRVDR_FIPS_ST_CD]  CHAR (2)        NULL,
    [CLM_PRVDR_SPCLTY_CD]     CHAR (2)        NULL,
    [CLM_FED_TYPE_SRVC_CD]    CHAR (1)        NULL,
    [CLM_POS_CD]              CHAR (2)        NULL,
    [CLM_LINE_FROM_DT]        DATE            NULL,
    [CLM_LINE_THRU_DT]        DATE            NULL,
    [CLM_LINE_HCPCS_CD]       VARCHAR (5)     NULL,
    [CLM_LINE_CVRD_PD_AMT]    VARCHAR (15)    NULL,
    [CLM_LINE_PRMRY_PYR_CD]   CHAR (1)        NULL,
    [CLM_LINE_DGNS_CD]        VARCHAR (7)     NULL,
    [RNDRG_PRVDR_NPI_NUM]     VARCHAR (10)    NULL,
    [CLM_CARR_PMT_DNL_CD]     CHAR (2)        NULL,
    [CLM_PRCSG_IND_CD]        CHAR (2)        NULL,
    [CLM_ADJSMT_TYPE_CD]      CHAR (2)        NULL,
    [CLM_EFCTV_DT]            DATE            NULL,
    [CLM_IDR_LD_DT]           DATE            NULL,
    [CLM_CNTL_NUM]            VARCHAR (40)    NULL,
    [BENE_EQTBL_BIC_HICN_NUM] VARCHAR (11)    NULL,
    [CLM_LINE_ALOWD_CHRG_AMT] VARCHAR (17)    NULL,
    [CLM_LINE_SRVC_UNIT_QTY]  NUMERIC (18, 3) NULL,
    [HCPCS_1_MDFR_CD]         CHAR (2)        NULL,
    [HCPCS_2_MDFR_CD]         CHAR (2)        NULL,
    [HCPCS_3_MDFR_CD]         CHAR (2)        NULL,
    [HCPCS_4_MDFR_CD]         CHAR (2)        NULL,
    [HCPCS_5_MDFR_CD]         CHAR (2)        NULL,
    [CLM_DISP_CD]             CHAR (2)        NULL,
    [CLM_DGNS_1_CD]           VARCHAR (7)     NULL,
    [CLM_DGNS_2_CD]           VARCHAR (7)     NULL,
    [CLM_DGNS_3_CD]           VARCHAR (7)     NULL,
    [CLM_DGNS_4_CD]           VARCHAR (7)     NULL,
    [CLM_DGNS_5_CD]           VARCHAR (7)     NULL,
    [CLM_DGNS_6_CD]           VARCHAR (7)     NULL,
    [CLM_DGNS_7_CD]           VARCHAR (7)     NULL,
    [CLM_DGNS_8_CD]           VARCHAR (7)     NULL,
    [DGNS_PRCDR_ICD_IND]      CHAR (1)        NULL,
    [SrcFileName]             VARCHAR (100)   NULL,
    [FileDate]                DATE            NULL,
    [OriginalFileName]        VARCHAR (100)   NULL,
    [CreateDate]              DATETIME        NULL,
    [CreateBy]                VARCHAR (100)   NULL,
    [BENE_MBI_ID]             VARCHAR (11)    NULL,
    [CLM_DGNS_9_CD]           VARCHAR (7)     NULL,
    [CLM_DGNS_10_CD]          VARCHAR (7)     NULL,
    [CLM_DGNS_11_CD]          VARCHAR (7)     NULL,
    [CLM_DGNS_12_CD]          VARCHAR (7)     NULL,
    [HCPCS_BETOS_CD]          VARCHAR (3)     NULL,
    [CLM_RNDRG_PRVDR_TAX_NUM] VARCHAR (10)    NULL,
    PRIMARY KEY CLUSTERED ([URN] ASC)
);




GO
CREATE NONCLUSTERED INDEX [_dta_index_CCLF5_15_1526296497__K45D_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32_33_]
    ON [adi].[CCLF5]([FileDate] DESC)
    INCLUDE([URN], [CUR_CLM_UNIQ_ID], [CLM_LINE_NUM], [BENE_HIC_NUM], [CLM_TYPE_CD], [CLM_FROM_DT], [CLM_THRU_DT], [RNDRG_PRVDR_TYPE_CD], [RNDRG_PRVDR_FIPS_ST_CD], [CLM_PRVDR_SPCLTY_CD], [CLM_FED_TYPE_SRVC_CD], [CLM_POS_CD], [CLM_LINE_FROM_DT], [CLM_LINE_THRU_DT], [CLM_LINE_HCPCS_CD], [CLM_LINE_CVRD_PD_AMT], [CLM_LINE_PRMRY_PYR_CD], [CLM_LINE_DGNS_CD], [RNDRG_PRVDR_NPI_NUM], [CLM_CARR_PMT_DNL_CD], [CLM_PRCSG_IND_CD], [CLM_ADJSMT_TYPE_CD], [CLM_EFCTV_DT], [CLM_IDR_LD_DT], [CLM_CNTL_NUM], [BENE_EQTBL_BIC_HICN_NUM], [CLM_LINE_ALOWD_CHRG_AMT], [CLM_LINE_SRVC_UNIT_QTY], [HCPCS_1_MDFR_CD], [HCPCS_2_MDFR_CD], [HCPCS_3_MDFR_CD], [HCPCS_4_MDFR_CD], [HCPCS_5_MDFR_CD], [CLM_DISP_CD], [CLM_DGNS_1_CD], [CLM_DGNS_2_CD], [CLM_DGNS_3_CD], [CLM_DGNS_4_CD], [CLM_DGNS_5_CD], [CLM_DGNS_6_CD], [CLM_DGNS_7_CD], [CLM_DGNS_8_CD], [DGNS_PRCDR_ICD_IND], [SrcFileName], [OriginalFileName], [CreateDate], [CreateBy], [BENE_MBI_ID], [CLM_DGNS_9_CD], [CLM_DGNS_10_CD], [CLM_DGNS_11_CD], [CLM_DGNS_12_CD], [HCPCS_BETOS_CD], [CLM_RNDRG_PRVDR_TAX_NUM]);


GO
CREATE NONCLUSTERED INDEX [_dta_index_CCLF5_15_1526296497__K45_K2_K3_1]
    ON [adi].[CCLF5]([FileDate] ASC, [CUR_CLM_UNIQ_ID] ASC, [CLM_LINE_NUM] ASC)
    INCLUDE([URN]);


GO
CREATE NONCLUSTERED INDEX [_dta_index_CCLF5_15_1526296497__K3_K1_2_4_12_13_14_15_16_25_28_29_30_31_32_35_36_37_38_39_40_41_42_43]
    ON [adi].[CCLF5]([CLM_LINE_NUM] ASC, [URN] ASC)
    INCLUDE([CUR_CLM_UNIQ_ID], [BENE_HIC_NUM], [CLM_POS_CD], [CLM_LINE_FROM_DT], [CLM_LINE_THRU_DT], [CLM_LINE_HCPCS_CD], [CLM_LINE_CVRD_PD_AMT], [CLM_CNTL_NUM], [CLM_LINE_SRVC_UNIT_QTY], [HCPCS_1_MDFR_CD], [HCPCS_2_MDFR_CD], [HCPCS_3_MDFR_CD], [HCPCS_4_MDFR_CD], [CLM_DGNS_1_CD], [CLM_DGNS_2_CD], [CLM_DGNS_3_CD], [CLM_DGNS_4_CD], [CLM_DGNS_5_CD], [CLM_DGNS_6_CD], [CLM_DGNS_7_CD], [CLM_DGNS_8_CD], [DGNS_PRCDR_ICD_IND]);


GO
CREATE NONCLUSTERED INDEX [_dta_index_CCLF5_15_1526296497__K3_1_2_4_6_7_8_10_18_19_20_25_26]
    ON [adi].[CCLF5]([CLM_LINE_NUM] ASC)
    INCLUDE([URN], [CUR_CLM_UNIQ_ID], [BENE_HIC_NUM], [CLM_FROM_DT], [CLM_THRU_DT], [RNDRG_PRVDR_TYPE_CD], [CLM_PRVDR_SPCLTY_CD], [CLM_LINE_DGNS_CD], [RNDRG_PRVDR_NPI_NUM], [CLM_CARR_PMT_DNL_CD], [CLM_CNTL_NUM], [BENE_EQTBL_BIC_HICN_NUM]);


GO
CREATE STATISTICS [_dta_stat_1526296497_45_2_3_1]
    ON [adi].[CCLF5]([FileDate], [CUR_CLM_UNIQ_ID], [CLM_LINE_NUM], [URN]);


GO
CREATE STATISTICS [_dta_stat_1526296497_2_3]
    ON [adi].[CCLF5]([CUR_CLM_UNIQ_ID], [CLM_LINE_NUM]);


GO
CREATE STATISTICS [_dta_stat_1526296497_1_45_2]
    ON [adi].[CCLF5]([URN], [FileDate], [CUR_CLM_UNIQ_ID]);


GO
CREATE STATISTICS [_dta_stat_1526296497_1_2_3]
    ON [adi].[CCLF5]([URN], [CUR_CLM_UNIQ_ID], [CLM_LINE_NUM]);

