CREATE TABLE [adi].[copAceWorkList] (
    [copAceWorklistKey]             INT           IDENTITY (1, 1) NOT NULL,
    [srcFileName]                   VARCHAR (150) NOT NULL,
    [loadDate]                      DATE          NOT NULL,
    [CreatedDate]                   DATE          CONSTRAINT [DF_adiCopAceWorkList_CreateDate] DEFAULT (getdate()) NOT NULL,
    [CreatedBy]                     VARCHAR (50)  CONSTRAINT [DF_adiCopAceWorkList_CreateBy] DEFAULT (suser_sname()) NOT NULL,
    [Subscriber_ID]                 VARCHAR (50)  NULL,
    [Total_Gaps]                    INT           NULL,
    [Provider_Name]                 VARCHAR (150) NULL,
    [Last_Service_Date_for_Measure] DATE          NULL,
    [Member_Name]                   VARCHAR (150) NULL,
    [Member_DOB]                    DATE          NULL,
    [Member_Zip]                    VARCHAR (15)  NULL,
    [NPI]                           VARCHAR (15)  NULL,
    [Measure]                       VARCHAR (MAX) NULL,
    [Plan]                          VARCHAR (20)  NULL,
    [Member_Phone]                  VARCHAR (35)  NULL,
    [PCP_Phone]                     CHAR (200)    NULL,
    [Last_Call_Date]                DATE          NULL,
    [Last_Outcome]                  VARCHAR (15)  NULL,
    [First_Call_Date]               DATE          NULL,
    [First_Call_Outcome]            VARCHAR (200) NULL,
    [Second_Call_Date]              DATE          NULL,
    [Second_Call_Outcome]           VARCHAR (200) NULL,
    [Third_Call_Date]               DATE          NULL,
    [Third_Call_Outcome]            VARCHAR (200) NULL,
    [Fourth_Call_Date]              VARCHAR (15)  NULL,
    [Fourth_Call_Outcome]           VARCHAR (200) NULL,
    [File_Update_Date]              DATE          NULL,
    [List_Generated_Date]           DATE          NULL,
    [Comments]                      VARCHAR (MAX) NULL,
    [First_Call_Type]               VARCHAR (20)  NULL,
    [Second_Call_Type]              VARCHAR (20)  NULL,
    [Third_Call_Type]               VARCHAR (20)  NULL,
    [Fourth_Call_Type]              VARCHAR (20)  NULL,
    [Latest_Outcome]                VARCHAR (500) NULL,
    [Latest_Action]                 VARCHAR (100) NULL,
    [Latest_Action_Date]            VARCHAR (12)  NULL,
    [Latest_Rep]                    VARCHAR (50)  NULL,
    [Priority_Weight]               INT           NULL,
    [PCPAddress]                    VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([copAceWorklistKey] ASC)
);

