CREATE TABLE [adi].[H_CCLF8] (
    [URN]                      INT           IDENTITY (1, 1) NOT NULL,
    [BENE_HIC_NUM]             VARCHAR (22)  NULL,
    [BENE_FIPS_STATE_CD]       VARCHAR (2)   NULL,
    [BENE_FIPS_CNTY_CD]        VARCHAR (3)   NULL,
    [BENE_ZIP_CD]              VARCHAR (5)   NULL,
    [BENE_DOB]                 VARCHAR (10)  NULL,
    [BENE_SEX_CD]              VARCHAR (1)   NULL,
    [BENE_RACE_CD]             VARCHAR (1)   NULL,
    [BENE_AGE]                 VARCHAR (3)   NULL,
    [BENE_MDCR_STUS_CD]        VARCHAR (2)   NULL,
    [BENE_DUAL_STUS_CD]        VARCHAR (2)   NULL,
    [BENE_DEATH_DT]            VARCHAR (10)  NULL,
    [BENE_RNG_BGN_DT]          VARCHAR (10)  NULL,
    [BENE_RNG_END_DT]          VARCHAR (10)  NULL,
    [BENE_1ST_NAME]            VARCHAR (30)  NULL,
    [BENE_MIDL_NAME]           VARCHAR (15)  NULL,
    [BENE_LAST_NAME]           VARCHAR (40)  NULL,
    [BENE_ORGNL_ENTLMT_RSN_CD] VARCHAR (1)   NULL,
    [BENE_ENTL_MT_BUYIN_IND]   VARCHAR (1)   NULL,
    [SrcFileName]              VARCHAR (100) NULL,
    [FileDate]                 DATE          NULL,
    [CreateDate]               DATETIME      NULL,
    [CreateBy]                 VARCHAR (100) NULL,
    [OriginalFileName]         VARCHAR (100) NULL,
    [BENE_RNG_A_BGN_DT]        DATETIME      NULL,
    [BENE_RNG_B_BGN_DT]        DATETIME      NULL,
    [BENE_LINE_1_ADR]          VARCHAR (45)  NULL,
    [BENE_LINE_2_ADR]          VARCHAR (45)  NULL,
    [BENE_LINE_3_ADR]          VARCHAR (40)  NULL,
    [BENE_LINE_4_ADR]          VARCHAR (40)  NULL,
    [BENE_LINE_5_ADR]          VARCHAR (40)  NULL,
    [BENE_LINE_6_ADR]          VARCHAR (40)  NULL,
    [GEO_ZIP_PLC_NAME]         VARCHAR (100) NULL,
    [GEO_USPS_STATE_CD]        VARCHAR (2)   NULL,
    [GEO_ZIP5_CD]              VARCHAR (5)   NULL,
    [GEO_ZIP4_CD]              VARCHAR (4)   NULL,
    [BENE_MBI_ID]              VARCHAR (11)  NULL,
    PRIMARY KEY CLUSTERED ([URN] ASC)
);

