CREATE TABLE [adi].[z.ALR.QASSGNT1] (
    [QASSGNT1Key]        INT           NOT NULL,
    [OriginalFileName]   VARCHAR (100) NOT NULL,
    [SrcFileName]        VARCHAR (100) NOT NULL,
    [LoadDate]           DATE          DEFAULT (sysdatetime()) NOT NULL,
    [CreatedDate]        DATE          NOT NULL,
    [CreatedBy]          VARCHAR (50)  NOT NULL,
    [LastUpdatedDate]    SMALLDATETIME NOT NULL,
    [LastUpdatedBy]      VARCHAR (50)  NOT NULL,
    [MBI]                VARCHAR (11)  NULL,
    [HICN]               VARCHAR (12)  NULL,
    [FirstName]          VARCHAR (30)  NULL,
    [LastName]           VARCHAR (40)  NULL,
    [Sex]                VARCHAR (1)   NULL,
    [DOB]                VARCHAR (10)  NULL,
    [DOD]                VARCHAR (10)  NULL,
    [CountyName]         VARCHAR (100) NULL,
    [StateName]          VARCHAR (100) NULL,
    [CountyNumber]       VARCHAR (5)   NULL,
    [VoluntaryFlag]      VARCHAR (8)   NULL,
    [CBFlag]             VARCHAR (8)   NULL,
    [CBStepFlag]         VARCHAR (8)   NULL,
    [PrevBenFlag]        VARCHAR (8)   NULL,
    [HCC1]               VARCHAR (1)   NULL,
    [HCC2]               VARCHAR (1)   NULL,
    [HCC6]               VARCHAR (1)   NULL,
    [HCC8]               VARCHAR (1)   NULL,
    [HCC9]               VARCHAR (1)   NULL,
    [HCC10]              VARCHAR (1)   NULL,
    [HCC11]              VARCHAR (1)   NULL,
    [HCC12]              VARCHAR (1)   NULL,
    [HCC17 ]             VARCHAR (1)   NULL,
    [HCC18 ]             VARCHAR (1)   NULL,
    [HCC19 ]             VARCHAR (1)   NULL,
    [HCC21 ]             VARCHAR (1)   NULL,
    [HCC22 ]             VARCHAR (1)   NULL,
    [HCC23 ]             VARCHAR (1)   NULL,
    [HCC27 ]             VARCHAR (1)   NULL,
    [HCC28 ]             VARCHAR (1)   NULL,
    [HCC29 ]             VARCHAR (1)   NULL,
    [HCC33 ]             VARCHAR (1)   NULL,
    [HCC34 ]             VARCHAR (1)   NULL,
    [HCC35 ]             VARCHAR (1)   NULL,
    [HCC39 ]             VARCHAR (1)   NULL,
    [HCC40 ]             VARCHAR (1)   NULL,
    [HCC46 ]             VARCHAR (1)   NULL,
    [HCC47 ]             VARCHAR (1)   NULL,
    [HCC48 ]             VARCHAR (1)   NULL,
    [HCC54 ]             VARCHAR (1)   NULL,
    [HCC55 ]             VARCHAR (1)   NULL,
    [HCC57 ]             VARCHAR (1)   NULL,
    [HCC58 ]             VARCHAR (1)   NULL,
    [HCC70 ]             VARCHAR (1)   NULL,
    [HCC71 ]             VARCHAR (1)   NULL,
    [HCC72 ]             VARCHAR (1)   NULL,
    [HCC73 ]             VARCHAR (1)   NULL,
    [HCC74 ]             VARCHAR (1)   NULL,
    [HCC75 ]             VARCHAR (1)   NULL,
    [HCC76 ]             VARCHAR (1)   NULL,
    [HCC77 ]             VARCHAR (1)   NULL,
    [HCC78 ]             VARCHAR (1)   NULL,
    [HCC79 ]             VARCHAR (1)   NULL,
    [HCC80 ]             VARCHAR (1)   NULL,
    [HCC82 ]             VARCHAR (1)   NULL,
    [HCC83 ]             VARCHAR (1)   NULL,
    [HCC84 ]             VARCHAR (1)   NULL,
    [HCC85 ]             VARCHAR (1)   NULL,
    [HCC86 ]             VARCHAR (1)   NULL,
    [HCC87 ]             VARCHAR (1)   NULL,
    [HCC88 ]             VARCHAR (1)   NULL,
    [HCC96 ]             VARCHAR (1)   NULL,
    [HCC99 ]             VARCHAR (1)   NULL,
    [HCC100 ]            VARCHAR (1)   NULL,
    [HCC103 ]            VARCHAR (1)   NULL,
    [HCC104 ]            VARCHAR (1)   NULL,
    [HCC106 ]            VARCHAR (1)   NULL,
    [HCC107 ]            VARCHAR (1)   NULL,
    [HCC108 ]            VARCHAR (1)   NULL,
    [HCC110 ]            VARCHAR (1)   NULL,
    [HCC111 ]            VARCHAR (1)   NULL,
    [HCC112 ]            VARCHAR (1)   NULL,
    [HCC114 ]            VARCHAR (1)   NULL,
    [HCC115 ]            VARCHAR (1)   NULL,
    [HCC122 ]            VARCHAR (1)   NULL,
    [HCC124 ]            VARCHAR (1)   NULL,
    [HCC134 ]            VARCHAR (1)   NULL,
    [HCC135 ]            VARCHAR (1)   NULL,
    [HCC136 ]            VARCHAR (1)   NULL,
    [HCC137 ]            VARCHAR (1)   NULL,
    [HCC157 ]            VARCHAR (1)   NULL,
    [HCC158 ]            VARCHAR (1)   NULL,
    [HCC161 ]            VARCHAR (1)   NULL,
    [HCC162 ]            VARCHAR (1)   NULL,
    [HCC166 ]            VARCHAR (1)   NULL,
    [HCC167 ]            VARCHAR (1)   NULL,
    [HCC169 ]            VARCHAR (1)   NULL,
    [HCC170 ]            VARCHAR (1)   NULL,
    [HCC173 ]            VARCHAR (1)   NULL,
    [HCC176 ]            VARCHAR (1)   NULL,
    [HCC186 ]            VARCHAR (1)   NULL,
    [HCC188 ]            VARCHAR (1)   NULL,
    [HCC189 ]            VARCHAR (1)   NULL,
    [PartDFlag]          VARCHAR (50)  NULL,
    [RS_ESRD]            VARCHAR (8)   NULL,
    [RS_Disabled]        VARCHAR (50)  NULL,
    [RS_AgedDual]        VARCHAR (50)  NULL,
    [RS_AgedNonDual]     VARCHAR (50)  NULL,
    [Dem_RS_ESRD]        VARCHAR (8)   NULL,
    [Dem_RS_Disabled]    VARCHAR (50)  NULL,
    [Dem_RS_AgedDual]    VARCHAR (50)  NULL,
    [Dem_RS_AgedNonDual] VARCHAR (50)  NULL,
    [EnrollFlag1]        VARCHAR (8)   NULL,
    [EnrollFlag2]        VARCHAR (8)   NULL,
    [EnrollFlag3]        VARCHAR (8)   NULL,
    [EnrollFlag4]        VARCHAR (8)   NULL,
    [EnrollFlag5]        VARCHAR (8)   NULL,
    [EnrollFlag6]        VARCHAR (8)   NULL,
    [EnrollFlag7]        VARCHAR (8)   NULL,
    [EnrollFlag8]        VARCHAR (8)   NULL,
    [EnrollFlag9]        VARCHAR (8)   NULL,
    [EnrollFlag10]       VARCHAR (8)   NULL,
    [EnrollFlag11]       VARCHAR (8)   NULL,
    [EnrollFlag12]       VARCHAR (8)   NULL
);


GO
CREATE CLUSTERED INDEX [_dta_index_ALR.QASSGNT1_c_15_1076250939__K4]
    ON [adi].[z.ALR.QASSGNT1]([LoadDate] ASC);


GO
CREATE STATISTICS [_dta_stat_1076250939_88_4]
    ON [adi].[z.ALR.QASSGNT1]([HCC137 ], [LoadDate]);

