USE [ACDW_CLMS_CCACO]
GO
TRUNCATE TABLE adw.[Member_History]


INSERT INTO adw.[Member_History]
           ([MBI]
           ,[HICN]
           ,[FirstName]
           ,[LastName]
           ,[Sex]
           ,[DOB]
           ,[DOD]
           ,[CountyName]
           ,[StateName]
           ,[CountyNumber]
           ,[VoluntaryFlag]
           ,[CBFlag]
           ,[CBStepFlag]
           ,[PrevBenFlag]
           ,[HCC1]
           ,[HCC2]
           ,[HCC6]
           ,[HCC8]
           ,[HCC9]
           ,[HCC10]
           ,[HCC11]
           ,[HCC12]
           ,[HCC17]
           ,[HCC18]
           ,[HCC19]
           ,[HCC21]
           ,[HCC22]
           ,[HCC23]
           ,[HCC27]
           ,[HCC28]
           ,[HCC29]
           ,[HCC33]
           ,[HCC34]
           ,[HCC35]
           ,[HCC39]
           ,[HCC40]
           ,[HCC46]
           ,[HCC47]
           ,[HCC48]
           ,[HCC54]
           ,[HCC55]
           ,[HCC57]
           ,[HCC58]
           ,[HCC70]
           ,[HCC71]
           ,[HCC72]
           ,[HCC73]
           ,[HCC74]
           ,[HCC75]
           ,[HCC76]
           ,[HCC77]
           ,[HCC78]
           ,[HCC79]
           ,[HCC80]
           ,[HCC82]
           ,[HCC83]
           ,[HCC84]
           ,[HCC85]
           ,[HCC86]
           ,[HCC87]
           ,[HCC88]
           ,[HCC96]
           ,[HCC99]
           ,[HCC100]
           ,[HCC103]
           ,[HCC104]
           ,[HCC106]
           ,[HCC107]
           ,[HCC108]
           ,[HCC110]
           ,[HCC111]
           ,[HCC112]
           ,[HCC114]
           ,[HCC115]
           ,[HCC122]
           ,[HCC124]
           ,[HCC134]
           ,[HCC135]
           ,[HCC136]
           ,[HCC137]
           ,[HCC157]
           ,[HCC158]
           ,[HCC161]
           ,[HCC162]
           ,[HCC166]
           ,[HCC167]
           ,[HCC169]
           ,[HCC170]
           ,[HCC173]
           ,[HCC176]
           ,[HCC186]
           ,[HCC188]
           ,[HCC189]
           ,[PartDFlag]
           ,[RS_ESRD]
           ,[RS_Disabled]
           ,[RS_AgedDual]
           ,[RS_AgedNonDual]
           ,[Demo_RS_ESRD]
           ,[Demo_RS_Disabled]
           ,[Demo_RS_AgedDual]
           ,[Demo_RS_AgedNonDual]
           ,[ESRD_RS]
           ,[DISABLED_RS]
           ,[DUAL_RS]
           ,[NONDUAL_RS]
           ,[ELIG_TYPE]
           ,[MBR_YEAR]
           ,[MBR_QTR]
           ,[LOAD_DATE]
           ,[LOAD_USER]
		   ,[EnrollFlag1]
		   ,[EnrollFlag2] 
			,[EnrollFlag3] 
			,[EnrollFlag4] 
			,[EnrollFlag5] 
			,[EnrollFlag6] 
			,[EnrollFlag7] 
			,[EnrollFlag8] 
			,[EnrollFlag9] 
			,[EnrollFlag10]
			,[EnrollFlag11]
			,[EnrollFlag12])
    SELECT [MBI]
      ,[HICN]
	  ,[FirstName]
      ,[LastName]
      ,LEFT([Sex],1)
      ,CAST([DOB] as date)
      ,[DOD]
      ,[CountyName]
      ,[StateName]
      ,[CountyNumber]
      ,RTRIM([VoluntaryFlag])
      ,RTRIM([CBFlag])
      ,RTRIM([CBStepFlag])
      ,RTRIM([PrevBenFlag])
      ,[HCC1]
      ,[HCC2]
      ,[HCC6]
      ,[HCC8]
      ,[HCC9]
      ,[HCC10]
      ,[HCC11]
      ,[HCC12]
      ,[HCC17 ]
      ,[HCC18 ]
      ,[HCC19 ]
      ,[HCC21 ]
      ,[HCC22 ]
      ,[HCC23 ]
      ,[HCC27 ]
      ,[HCC28 ]
      ,[HCC29 ]
      ,[HCC33 ]
      ,[HCC34 ]
      ,[HCC35 ]
      ,[HCC39 ]
      ,[HCC40 ]
      ,[HCC46 ]
      ,[HCC47 ]
      ,[HCC48 ]
      ,[HCC54 ]
      ,[HCC55 ]
      ,[HCC57 ]
      ,[HCC58 ]
      ,[HCC70 ]
      ,[HCC71 ]
      ,[HCC72 ]
      ,[HCC73 ]
      ,[HCC74 ]
      ,[HCC75 ]
      ,[HCC76 ]
      ,[HCC77 ]
      ,[HCC78 ]
      ,[HCC79 ]
      ,[HCC80 ]
      ,[HCC82 ]
      ,[HCC83 ]
      ,[HCC84 ]
      ,[HCC85 ]
      ,[HCC86 ]
      ,[HCC87 ]
      ,[HCC88 ]
      ,[HCC96 ]
      ,[HCC99 ]
      ,[HCC100 ]
      ,[HCC103 ]
      ,[HCC104 ]
      ,[HCC106 ]
      ,[HCC107 ]
      ,[HCC108 ]
      ,[HCC110 ]
      ,[HCC111 ]
      ,[HCC112 ]
      ,[HCC114 ]
      ,[HCC115 ]
      ,[HCC122 ]
      ,[HCC124 ]
      ,[HCC134 ]
      ,[HCC135 ]
      ,[HCC136 ]
      ,[HCC137 ]
      ,[HCC157 ]
      ,[HCC158 ]
      ,[HCC161 ]
      ,[HCC162 ]
      ,[HCC166 ]
      ,[HCC167 ]
      ,[HCC169 ]
      ,[HCC170 ]
      ,[HCC173 ]
      ,[HCC176 ]
      ,[HCC186 ]
      ,[HCC188 ]
      ,[HCC189 ]
      ,LEFT(RTRIM([PartDFlag]),1)
      ,CAST ([RS_ESRD] as decimal (5,4))
      ,CAST ([RS_Disabled] as decimal (5,4))
      ,CAST ([RS_AgedDual] as decimal (5,4))
      ,CAST ([RS_AgedNonDual] as decimal (5,4))
      ,CAST ([Demo_RS_ESRD] as decimal (5,4))
      ,CAST ([Demo_RS_Disabled] as decimal (5,4))
      ,CAST ([Demo_RS_AgedDual] as decimal (5,4))
      ,CAST ([Demo_RS_AgedNonDual]as decimal (5,4))
	  ,ISNULL([RS_ESRD],0) + ISNULL([Demo_RS_ESRD],0) AS ESRD_RS
	  ,ISNULL([RS_Disabled],0) + ISNULL([Demo_RS_Disabled],0) AS DISABLED_RS
	  ,ISNULL([RS_AgedDual],0) + ISNULL([Demo_RS_AgedDual],0) AS DUAL_RS
	  ,ISNULL([RS_AgedNonDual],0) + ISNULL([Demo_RS_AgedNonDual],0) AS NONDUAL_RS
	  ,CASE  WHEN ISNULL([RS_ESRD],0) + ISNULL([Demo_RS_ESRD],0) > 0 THEN '1' 
	  WHEN ISNULL([RS_Disabled],0) + ISNULL([Demo_RS_Disabled],0) > 0 THEN '2' 
	  WHEN ISNULL([RS_AgedDual],0) + ISNULL([Demo_RS_AgedDual],0) > 0 THEN '3' 
	  WHEN ISNULL([RS_AgedNonDual],0) + ISNULL([Demo_RS_AgedNonDual],0) > 0 THEN '4' 
	  ELSE '0'
	  END AS ELIG_TYPE
      ,LEFT([EffQtr],4)
	  ,RIGHT([EffQtr],1)
	  ,CAST(getdate() as date)
	  ,suser_name()
	  ,[EnrollFlag1], 
	[EnrollFlag2] ,
	[EnrollFlag3] ,
	[EnrollFlag4] ,
	[EnrollFlag5] ,
	[EnrollFlag6] ,
	[EnrollFlag7] ,
	[EnrollFlag8] ,
	[EnrollFlag9] ,
	[EnrollFlag10],
	[EnrollFlag11],
	[EnrollFlag12]
  FROM ast.[QASSGNT1]
  	--WHERE EFFQTR = '2018Q3'


GO


