CREATE TABLE [lst].[LIST_PCP_PRACTICE] (
    [PCP_PRACTICE_URN]       BIGINT        IDENTITY (1, 1) NOT NULL,
    [CLIENT_ID]              VARCHAR (50)  NULL,
    [PCP_PRACTICE_TIN]       VARCHAR (50)  NULL,
    [PCP_PRACTICE_NAME]      VARCHAR (150) NULL,
    [PCP_PRACTICE_CLIENT_ID] VARCHAR (50)  NULL,
    [PCP_PRACTICE_ADDRESS]   VARCHAR (100) NULL,
    [PCP_PRACTICE_ADDRESS2]  VARCHAR (50)  NULL,
    [PCP_PRACTICE_CITY]      VARCHAR (50)  NULL,
    [PCP_PRACTICE_STATE]     VARCHAR (50)  NULL,
    [PCP_PRACTICE_ZIP]       VARCHAR (50)  NULL,
    [PCP_PRACTICE_PHONE1]    VARCHAR (50)  NULL,
    [PCP_PRACTICE_PHONE2]    VARCHAR (50)  NULL,
    [PCP_PRACTICE_NPI]       VARCHAR (50)  NULL,
    [ACTIVE]                 VARCHAR (50)  NULL,
    [LOAD_DATE]              VARCHAR (50)  NULL,
    [LOAD_USER]              VARCHAR (50)  NULL,
    [CAMPAIGN_RUN_ID]        INT           NULL,
    [T_Modify_by]            VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([PCP_PRACTICE_URN] ASC)
);

