


CREATE PROCEDURE [dbo].[z_SP_QM_MASTER]
as
EXEC adw.[SP_QM_ABA]
EXEC adw.[SP_QM_ART]
EXEC adw.[SP_QM_AWC]
EXEC adw.[SP_QM_BCS]
EXEC adw.[SP_QM_CCS]
EXEC adw.[SP_QM_CDC_8]
EXEC adw.[SP_QM_CDC_9]
EXEC adw.[SP_QM_CDC_BP]
EXEC adw.[SP_QM_CDC_E]
EXEC adw.[SP_QM_CDC_HB]
EXEC adw.[SP_QM_CDC_N]
EXEC adw.[SP_QM_COL]
EXEC adw.[SP_QM_PCE_B]
EXEC adw.[SP_QM_PCE_S]
EXEC adw.[SP_QM_SPR]
EXEC adw.[SP_QM_WC0]
EXEC adw.[SP_QM_WC1]
EXEC adw.[SP_QM_WC2]
EXEC adw.[SP_QM_WC3]
EXEC adw.[SP_QM_WC4]
EXEC adw.[SP_QM_WC5]
EXEC adw.[SP_QM_WC6]
EXEC adw.[SP_QM_WC36]




--EXEC [SP_QM_CDC_7]
