CREATE TABLE [ast].[CCLF8_Updates] (
    [BENE_HIC_NUM]             VARCHAR (22)  NOT NULL,
    [BENE_FIPS_STATE_CD]       SMALLINT      NULL,
    [BENE_FIPS_CNTY_CD]        SMALLINT      NULL,
    [BENE_ZIP_CD]              VARCHAR (11)  NULL,
    [BENE_DOB]                 DATE          NULL,
    [BENE_SEX_CD]              CHAR (2)      NULL,
    [BENE_RACE_CD]             CHAR (2)      NULL,
    [BENE_AGE]                 SMALLINT      NULL,
    [BENE_MDCR_STUS_CD]        VARCHAR (5)   NULL,
    [BENE_DUAL_STUS_CD]        VARCHAR (5)   NULL,
    [BENE_DEATH_DT]            DATE          NULL,
    [BENE_RNG_BGN_DT]          DATE          NULL,
    [BENE_RNG_END_DT]          DATE          NULL,
    [BENE_1ST_NAME]            VARCHAR (65)  NULL,
    [BENE_LAST_NAME]           VARCHAR (65)  NULL,
    [BENE_MIDL_NAME]           VARCHAR (65)  NULL,
    [BENE_ORGNL_ENTLMT_RSN_CD] SMALLINT      NULL,
    [BENE_ENTLMT_BUYIN_IND]    VARCHAR (5)   NULL,
    [SrcFileName]              VARCHAR (100) NULL,
    [FileDate]                 DATE          NULL,
    [OriginalFileName]         VARCHAR (100) NULL,
    [CreateDate]               DATETIME      NULL,
    [CreateBy]                 VARCHAR (100) NULL,
    [AstCreatedDate]           DATETIME      NULL,
    [AstCreatedBy]             VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([BENE_HIC_NUM] ASC)
);

