CREATE TABLE [ast].[QASSGNT1] (
    [MBI]                 VARCHAR (50)   NULL,
    [HICN]                VARCHAR (50)   NULL,
    [FirstName]           VARCHAR (50)   NULL,
    [LastName]            VARCHAR (50)   NULL,
    [Sex]                 VARCHAR (50)   NULL,
    [DOB]                 VARCHAR (50)   NULL,
    [DOD]                 VARCHAR (50)   NULL,
    [CountyName]          VARCHAR (50)   NULL,
    [StateName]           VARCHAR (50)   NULL,
    [CountyNumber]        VARCHAR (50)   NULL,
    [VoluntaryFlag]       VARCHAR (50)   NULL,
    [CBFlag]              VARCHAR (50)   NULL,
    [CBStepFlag]          VARCHAR (50)   NULL,
    [PrevBenFlag]         VARCHAR (50)   NULL,
    [HCC1]                VARCHAR (50)   NULL,
    [HCC2]                VARCHAR (50)   NULL,
    [HCC6]                VARCHAR (50)   NULL,
    [HCC8]                VARCHAR (50)   NULL,
    [HCC9]                VARCHAR (50)   NULL,
    [HCC10]               VARCHAR (50)   NULL,
    [HCC11]               VARCHAR (50)   NULL,
    [HCC12]               VARCHAR (50)   NULL,
    [HCC17 ]              VARCHAR (50)   NULL,
    [HCC18 ]              VARCHAR (50)   NULL,
    [HCC19 ]              VARCHAR (50)   NULL,
    [HCC21 ]              VARCHAR (50)   NULL,
    [HCC22 ]              VARCHAR (50)   NULL,
    [HCC23 ]              VARCHAR (50)   NULL,
    [HCC27 ]              VARCHAR (50)   NULL,
    [HCC28 ]              VARCHAR (50)   NULL,
    [HCC29 ]              VARCHAR (50)   NULL,
    [HCC33 ]              VARCHAR (50)   NULL,
    [HCC34 ]              VARCHAR (50)   NULL,
    [HCC35 ]              VARCHAR (50)   NULL,
    [HCC39 ]              VARCHAR (50)   NULL,
    [HCC40 ]              VARCHAR (50)   NULL,
    [HCC46 ]              VARCHAR (50)   NULL,
    [HCC47 ]              VARCHAR (50)   NULL,
    [HCC48 ]              VARCHAR (50)   NULL,
    [HCC54 ]              VARCHAR (50)   NULL,
    [HCC55 ]              VARCHAR (50)   NULL,
    [HCC57 ]              VARCHAR (50)   NULL,
    [HCC58 ]              VARCHAR (50)   NULL,
    [HCC70 ]              VARCHAR (50)   NULL,
    [HCC71 ]              VARCHAR (50)   NULL,
    [HCC72 ]              VARCHAR (50)   NULL,
    [HCC73 ]              VARCHAR (50)   NULL,
    [HCC74 ]              VARCHAR (50)   NULL,
    [HCC75 ]              VARCHAR (50)   NULL,
    [HCC76 ]              VARCHAR (50)   NULL,
    [HCC77 ]              VARCHAR (50)   NULL,
    [HCC78 ]              VARCHAR (50)   NULL,
    [HCC79 ]              VARCHAR (50)   NULL,
    [HCC80 ]              VARCHAR (50)   NULL,
    [HCC82 ]              VARCHAR (50)   NULL,
    [HCC83 ]              VARCHAR (50)   NULL,
    [HCC84 ]              VARCHAR (50)   NULL,
    [HCC85 ]              CHAR (1)       NULL,
    [HCC86 ]              CHAR (1)       NULL,
    [HCC87 ]              CHAR (1)       NULL,
    [HCC88 ]              CHAR (1)       NULL,
    [HCC96 ]              CHAR (1)       NULL,
    [HCC99 ]              CHAR (1)       NULL,
    [HCC100 ]             CHAR (1)       NULL,
    [HCC103 ]             CHAR (1)       NULL,
    [HCC104 ]             CHAR (1)       NULL,
    [HCC106 ]             CHAR (1)       NULL,
    [HCC107 ]             CHAR (1)       NULL,
    [HCC108 ]             CHAR (1)       NULL,
    [HCC110 ]             CHAR (1)       NULL,
    [HCC111 ]             CHAR (1)       NULL,
    [HCC112 ]             CHAR (1)       NULL,
    [HCC114 ]             CHAR (1)       NULL,
    [HCC115 ]             CHAR (1)       NULL,
    [HCC122 ]             CHAR (1)       NULL,
    [HCC124 ]             CHAR (1)       NULL,
    [HCC134 ]             CHAR (1)       NULL,
    [HCC135 ]             CHAR (1)       NULL,
    [HCC136 ]             CHAR (1)       NULL,
    [HCC137 ]             CHAR (1)       NULL,
    [HCC157 ]             CHAR (1)       NULL,
    [HCC158 ]             CHAR (1)       NULL,
    [HCC161 ]             CHAR (1)       NULL,
    [HCC162 ]             CHAR (1)       NULL,
    [HCC166 ]             CHAR (1)       NULL,
    [HCC167 ]             CHAR (1)       NULL,
    [HCC169 ]             CHAR (1)       NULL,
    [HCC170 ]             CHAR (1)       NULL,
    [HCC173 ]             CHAR (1)       NULL,
    [HCC176 ]             CHAR (1)       NULL,
    [HCC186 ]             CHAR (1)       NULL,
    [HCC188 ]             CHAR (1)       NULL,
    [HCC189 ]             CHAR (1)       NULL,
    [PartDFlag]           VARCHAR (50)   NULL,
    [RS_ESRD]             DECIMAL (5, 4) NULL,
    [RS_Disabled]         DECIMAL (5, 4) NULL,
    [RS_AgedDual]         DECIMAL (5, 4) NULL,
    [RS_AgedNonDual]      DECIMAL (5, 4) NULL,
    [Demo_RS_ESRD]        DECIMAL (5, 4) NULL,
    [Demo_RS_Disabled]    DECIMAL (5, 4) NULL,
    [Demo_RS_AgedDual]    DECIMAL (5, 4) NULL,
    [Demo_RS_AgedNonDual] DECIMAL (5, 4) NULL,
    [EffQtr]              VARCHAR (50)   NULL,
    [LOAD_DATE]           DATE           NULL,
    [LOAD_USER]           VARCHAR (50)   NULL,
    [EnrollFlag1]         VARCHAR (8)    NULL,
    [EnrollFlag2]         VARCHAR (8)    NULL,
    [EnrollFlag3]         VARCHAR (8)    NULL,
    [EnrollFlag4]         VARCHAR (8)    NULL,
    [EnrollFlag5]         VARCHAR (8)    NULL,
    [EnrollFlag6]         VARCHAR (8)    NULL,
    [EnrollFlag7]         VARCHAR (8)    NULL,
    [EnrollFlag8]         VARCHAR (8)    NULL,
    [EnrollFlag9]         VARCHAR (8)    NULL,
    [EnrollFlag10]        VARCHAR (8)    NULL,
    [EnrollFlag11]        VARCHAR (8)    NULL,
    [EnrollFlag12]        VARCHAR (8)    NULL
);




GO
CREATE STATISTICS [_dta_stat_1589632756_80_116]
    ON [ast].[QASSGNT1]([HCC137 ], [LOAD_DATE]);


GO
CREATE STATISTICS [_dta_stat_1589632756_2_103]
    ON [ast].[QASSGNT1]([HICN], [EffQtr]);

