CREATE TABLE [adw].[Member_History] (
    [URN]                 INT            IDENTITY (1, 1) NOT NULL,
    [MBI]                 VARCHAR (50)   NULL,
    [HICN]                VARCHAR (50)   NULL,
    [FIRSTNAME]           VARCHAR (50)   NULL,
    [LASTNAME]            VARCHAR (50)   NULL,
    [SEX]                 VARCHAR (5)    NULL,
    [DOB]                 DATE           NULL,
    [DOD]                 DATE           NULL,
    [CountyName]          VARCHAR (50)   NULL,
    [StateName]           VARCHAR (25)   NULL,
    [CountyNumber]        VARCHAR (10)   NULL,
    [VoluntaryFlag]       CHAR (1)       NULL,
    [CBFlag]              CHAR (1)       NULL,
    [CBStepFlag]          CHAR (1)       NULL,
    [PrevBenFlag]         CHAR (1)       NULL,
    [HCC1]                CHAR (1)       NULL,
    [HCC2]                CHAR (1)       NULL,
    [HCC6]                CHAR (1)       NULL,
    [HCC8]                CHAR (1)       NULL,
    [HCC9]                CHAR (1)       NULL,
    [HCC10]               CHAR (1)       NULL,
    [HCC11]               CHAR (1)       NULL,
    [HCC12]               CHAR (1)       NULL,
    [HCC17]               CHAR (1)       NULL,
    [HCC18]               CHAR (1)       NULL,
    [HCC19]               CHAR (1)       NULL,
    [HCC21]               CHAR (1)       NULL,
    [HCC22]               CHAR (1)       NULL,
    [HCC23]               CHAR (1)       NULL,
    [HCC27]               CHAR (1)       NULL,
    [HCC28]               CHAR (1)       NULL,
    [HCC29]               CHAR (1)       NULL,
    [HCC33]               CHAR (1)       NULL,
    [HCC34]               CHAR (1)       NULL,
    [HCC35]               CHAR (1)       NULL,
    [HCC39]               CHAR (1)       NULL,
    [HCC40]               CHAR (1)       NULL,
    [HCC46]               CHAR (1)       NULL,
    [HCC47]               CHAR (1)       NULL,
    [HCC48]               CHAR (1)       NULL,
    [HCC54]               CHAR (1)       NULL,
    [HCC55]               CHAR (1)       NULL,
    [HCC57]               CHAR (1)       NULL,
    [HCC58]               CHAR (1)       NULL,
    [HCC70]               CHAR (1)       NULL,
    [HCC71]               CHAR (1)       NULL,
    [HCC72]               CHAR (1)       NULL,
    [HCC73]               CHAR (1)       NULL,
    [HCC74]               CHAR (1)       NULL,
    [HCC75]               CHAR (1)       NULL,
    [HCC76]               CHAR (1)       NULL,
    [HCC77]               CHAR (1)       NULL,
    [HCC78]               CHAR (1)       NULL,
    [HCC79]               CHAR (1)       NULL,
    [HCC80]               CHAR (1)       NULL,
    [HCC82]               CHAR (1)       NULL,
    [HCC83]               CHAR (1)       NULL,
    [HCC84]               CHAR (1)       NULL,
    [HCC85]               CHAR (1)       NULL,
    [HCC86]               CHAR (1)       NULL,
    [HCC87]               CHAR (1)       NULL,
    [HCC88]               CHAR (1)       NULL,
    [HCC96]               CHAR (1)       NULL,
    [HCC99]               CHAR (1)       NULL,
    [HCC100]              CHAR (1)       NULL,
    [HCC103]              CHAR (1)       NULL,
    [HCC104]              CHAR (1)       NULL,
    [HCC106]              CHAR (1)       NULL,
    [HCC107]              CHAR (1)       NULL,
    [HCC108]              CHAR (1)       NULL,
    [HCC110]              CHAR (1)       NULL,
    [HCC111]              CHAR (1)       NULL,
    [HCC112]              CHAR (1)       NULL,
    [HCC114]              CHAR (1)       NULL,
    [HCC115]              CHAR (1)       NULL,
    [HCC122]              CHAR (1)       NULL,
    [HCC124]              CHAR (1)       NULL,
    [HCC134]              CHAR (1)       NULL,
    [HCC135]              CHAR (1)       NULL,
    [HCC136]              CHAR (1)       NULL,
    [HCC137]              CHAR (1)       NULL,
    [HCC157]              CHAR (1)       NULL,
    [HCC158]              CHAR (1)       NULL,
    [HCC161]              CHAR (1)       NULL,
    [HCC162]              CHAR (1)       NULL,
    [HCC166]              CHAR (1)       NULL,
    [HCC167]              CHAR (1)       NULL,
    [HCC169]              CHAR (1)       NULL,
    [HCC170]              CHAR (1)       NULL,
    [HCC173]              CHAR (1)       NULL,
    [HCC176]              CHAR (1)       NULL,
    [HCC186]              CHAR (1)       NULL,
    [HCC188]              CHAR (1)       NULL,
    [HCC189]              CHAR (1)       NULL,
    [PartDFlag]           VARCHAR (1)    NULL,
    [RS_ESRD]             DECIMAL (5, 4) NULL,
    [RS_Disabled]         DECIMAL (5, 4) NULL,
    [RS_AgedDual]         DECIMAL (5, 4) NULL,
    [RS_AgedNonDual]      DECIMAL (5, 4) NULL,
    [Demo_RS_ESRD]        DECIMAL (5, 4) NULL,
    [Demo_RS_Disabled]    DECIMAL (5, 4) NULL,
    [Demo_RS_AgedDual]    DECIMAL (5, 4) NULL,
    [Demo_RS_AgedNonDual] DECIMAL (5, 4) NULL,
    [ESRD_RS]             DECIMAL (5, 4) NULL,
    [DISABLED_RS]         DECIMAL (5, 4) NULL,
    [DUAL_RS]             DECIMAL (5, 4) NULL,
    [NONDUAL_RS]          DECIMAL (5, 4) NULL,
    [ELIG_TYPE]           VARCHAR (1)    NULL,
    [MBR_YEAR]            INT            NULL,
    [MBR_QTR]             INT            NULL,
    [LOAD_DATE]           DATE           NULL,
    [LOAD_USER]           VARCHAR (50)   NULL,
    PRIMARY KEY CLUSTERED ([URN] ASC)
);

