CREATE TABLE [adw].[WorklistSentHistoryTable] (
    [URN]                         INT            IDENTITY (1, 1) NOT NULL,
    [WorklistSentHistoryKey]      INT            NOT NULL,
    [WorklistSentHistoryBatchKey] INT            NOT NULL,
    [LOB]                         VARCHAR (50)   NULL,
    [ClientMemberKey]             VARCHAR (50)   NULL,
    [Member_Name]                 VARCHAR (100)  NULL,
    [MemberPhoneNumber]           VARCHAR (50)   NULL,
    [PCP_Name]                    VARCHAR (100)  NULL,
    [PcpPhoneNumber]              VARCHAR (50)   NULL,
    [PcpAddress]                  VARCHAR (100)  NULL,
    [Measures_Combined]           VARCHAR (1500) NULL,
    [Total_Gaps]                  INT            NULL,
    [First_Contact_Type]          VARCHAR (10)   NULL,
    [First_Contact_Type_Date]     DATE           NULL,
    [First_Contact_Outcome]       VARCHAR (255)  NULL,
    [Second_Contact_Type]         VARCHAR (10)   NULL,
    [Second_Contact_Type_Date]    DATE           NULL,
    [Second_Contact_Outcome]      VARCHAR (255)  NULL,
    [Third_Contact_Type]          VARCHAR (10)   NULL,
    [Third_Contact_Type_Date]     DATE           NULL,
    [Third_Contact_Outcome]       VARCHAR (255)  NULL,
    [Fourth_Contact_Type]         VARCHAR (10)   NULL,
    [Fourth_Contact_Type_Date]    DATE           NULL,
    [Fourth_Contact_Outcome]      VARCHAR (255)  NULL,
    [Rep_Comment]                 VARCHAR (255)  NULL,
    [Priority_Weight]             NUMERIC (18)   NULL,
    [Latest_Outcome]              VARCHAR (255)  NULL,
    [Latest_Action]               VARCHAR (10)   NULL,
    [Latest_Action_Date]          DATE           NULL,
    [Latest_Rep]                  VARCHAR (25)   NULL,
    [copCallCtrWorklistKey]       VARCHAR (25)   NULL,
    [SourceFileName]              NVARCHAR (255) NULL,
    [LoadDate]                    DATE           CONSTRAINT [DF_WorklistSentHistoryTable_LoadDate] DEFAULT (getdate()) NULL,
    [CreatedDate]                 DATETIME       CONSTRAINT [DF_WorklistSentHistoryTable_CreatedDate] DEFAULT (getdate()) NULL,
    [CreatedBy]                   VARCHAR (50)   CONSTRAINT [DF_WorklistSentHistoryTable_CreatedBy] DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]             DATETIME       CONSTRAINT [DF_WorklistSentHistoryTable_LastUpdatedDate] DEFAULT (getdate()) NULL,
    [LastUpdatedBy]               VARCHAR (50)   CONSTRAINT [DF_WorklistSentHistoryTable_LastUpdatedBy] DEFAULT (suser_sname()) NULL,
    CONSTRAINT [PK_WorklistSentHistory] PRIMARY KEY CLUSTERED ([URN] ASC)
);

